### PR TITLE
Add support for Python 3.12.

### PR DESCRIPTION
**Pull request by icemac**
Isort imports.

### CODE REVIEW

**Review by d-maurer — APPROVED** [review]

**Review by dataflake — APPROVED** [review]
not sure why the Pypy3 tests fail

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2023-11-14 02:42 -0800:
>@dataflake approved this pull request.
>
>not sure why the Pypy3 tests fail

This looks like the effect of a `print` statement
(likely in server code).
Usually, the (doc)test is likely already finished before the print
is executed; here, a special load condition likely has let it
happen during the `ZEO.DB` call.

**Comment by navytux** [comment]
@icemac, thanks for asking for review.

The first patch (`Add support for Python 3.12`) looks good to me.

The second patch (`Isort imports`): while I understand the rationale, when I look at the diff, for example at

```diff
-from ZODB.utils import p64, u64, z64, Lock, RLock
+from ZODB.utils import Lock
+from ZODB.utils import RLock
+from ZODB.utils import p64
+from ZODB.utils import u64
+from ZODB.utils import z64
```

to me it feels like the old version was better with higher signal to noise ratio.

But this is not a strong feeling and I won't object to this change if others find it convenient.

Kirill

**Comment by icemac** [comment]
> not sure why the Pypy3 tests fail

PyPy3 prints some texts to stdout on GHA which break the doctests. I am going to ignore these texts.

**Comment by icemac** [comment]
> But this is not a strong feeling and I won't object to this change if others find it convenient.

This is the default config for imports used in all other zopefoundation projects. We could change it here but I'd prefer not to do it.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
