### PR TITLE
Add support for Python 3.7.

### LINKED ISSUE #116: Officially support Python 3.7

### PR DESCRIPTION
**Pull request by icemac**
Additionally test PyPy3 on TravisCI.

Fixes #116.

### CODE REVIEW

**Comment by jamadden** [comment]
The previous build from 12 days ago [passed using zope.testrunner 4.8.1](https://travis-ci.org/zopefoundation/ZEO/jobs/436354153#L463). These builds with zope.testrunner 4.9.0 all fail in the same way:

```
[Parallel tests running in .testZeo-new_addr.test:
  Traceback (most recent call last):
  File "bin/test", line 38, in <module>
    '--test-path', '/ZEO/eggs/ZopeUndo-4.3-py3.5.egg',
  File "//ZEO/eggs/zope.testrunner-4.9-py3.5.egg/zope/testrunner/__init__.py", line 31, in run
    warnings=warnings)
  File "//ZEO/eggs/zope.testrunner-4.9-py3.5.egg/zope/testrunner/__init__.py", line 51, in run_internal
    runner.run()
  File "//ZEO/eggs/zope.testrunner-4.9-py3.5.egg/zope/testrunner/runner.py", line 191, in run
    self.run_tests()
  File "//ZEO/eggs/zope.testrunner-4.9-py3.5.egg/zope/testrunner/runner.py", line 315, in run_tests
    self.skipped, self.cwd)
  File "//ZEO/eggs/zope.testrunner-4.9-py3.5.egg/zope/testrunner/runner.py", line 726, in resume_tests
    stdout.write(output)
TypeError: a bytes-like object is required, not 'str'
```

I think we way be looking at a regression in zope.testrunner. [Line 726 was changed](https://github.com/zopefoundation/zope.testrunner/blame/master/src/zope/testrunner/runner.py#L726) by https://github.com/zopefoundation/zope.testrunner/pull/69 ; that PR is not mentioned in zope.testrunner's changes, but it seems relevant.

**Comment by mgedmin** [comment]
FWIW I can reproduce those `checkPackUndoLog` failures on master with `tox -e py27`.

**Comment by icemac** [comment]
Hm, running the tests sequentially does not reduce the number of failures. Anyone here who knows the code enough to fix the tests?

**Comment by jamadden** [comment]
With zope.testrunner 4.9.2, I can confirm that the parallel issues are fixed. All that remains are the pack [test failures](https://travis-ci.org/zopefoundation/ZEO/jobs/451770905#L997):
```
Failure in test checkPackUndoLog (ZEO.tests.testZEO.FileStorageClientHexTests)
Traceback (most recent call last):
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/home/travis/build/zopefoundation/ZEO/eggs/ZODB-5.5.1-py3.5.egg/ZODB/tests/util.py", line 265, in wrapper
    return func(*args, **kwargs)
  File "/home/travis/build/zopefoundation/ZEO/eggs/ZODB-5.5.1-py3.5.egg/ZODB/tests/PackableStorage.py", line 678, in checkPackUndoLog
    self.assertEqual(1, len(self._storage.undoLog()))
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/3.5.6/lib/python3.5/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
```

**Comment by jamadden** [comment]
@icemac I think the failing test is fixed in master. Can you please rebase?

**Comment by jamadden** [comment]
I’ve rerun the PR tests, which include master, a few times and have gotten some failures, largely timeouts. Perhaps for this repo, dropping parallel tests could be reconsidered?

**Comment by jamadden** [comment]
In addition to some random failures on other versions, there are some legit failures on Python 3.7, e.g.,

```
Error in test testClientBasics (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/tests.py", line 131, in testClientBasics
    wrapper, cache, loop, client, protocol, transport = self.start()
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/tests.py", line 99, in start
    self.setup_delegation(loop)
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 723, in setup_delegation
    self.client = Client(loop, *self.__args, **self.__kwargs)
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 369, in __init__
    self.disconnected(None)
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 419, in disconnected
    self.try_connecting()
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 438, in try_connecting
    for addr in self.addrs
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 438, in <listcomp>
    for addr in self.addrs
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 93, in __init__
    self.connect()
  File "/home/travis/build/zopefoundation/ZEO/src/ZEO/asyncio/client.py", line 127, in connect
    @cr.add_done_callback
TypeError: call_soon() got an unexpected keyword argument 'context'
```

I believe that's because our mock-implementation of an event loop, found in `ZEO.async.testing.Loop` doesn't accept the new keyword-only `context` argument that [was added  in 3.7](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon). The 'current context' is used if no context is specifically passed, and presumably somewhere down in the guts of the coroutine implementation that's being reified into an argument.

**Comment by icemac** [comment]
@jamadden Do you think my workaround for the Python 3.7 problem is okay, so this PR can get merged?

**Comment by jamadden** [comment]
> Do you think my workaround for the Python 3.7 problem is okay

LGTM! Thanks!

> so this PR can get merged?

I think we should try to restore back `-j99` (or something smaller, at least). The current build is taking 45 minutes (total runtime 3 hours), with individual jobs running for 8 minutes. Previously, the last good build on master ran in just 9 minutes (total runtime 40 minutes) with individual jobs running for 2--3 minutes. (I know I'm the one that suggested dropping it, but I didn't expect the runtime to balloon so much.)

**Comment by jamadden** [comment]
Thanks! That appears to be working, and shaved more than an hour off the test times (cutting the wall clock time in half).

**Pull request merged**
