### PR TITLE
Remove support for credentials

### PR DESCRIPTION
**Pull request by navytux**
--------
kirr:

	for discussion

	originally support for credentials was added in https://github.com/zopefoundation/ZEO/commit/dbb066d2
	(https://github.com/zopefoundation/ZEO/pull/53)

Extracted from https://github.com/zopefoundation/ZEO/pull/195

### CODE REVIEW

**Comment by navytux** [comment]
See _"d) removal of credentials support"_ in https://github.com/zopefoundation/ZEO/pull/195#issuecomment-1374901652 .

**Comment by dataflake** [comment]
The comments on #53 clearly says that the support was experimental and it talks about future clients. That future never arrived. It makes sense to remove that experiment.

**Review by dataflake — APPROVED** [review]

**Comment by navytux** [comment]
Jens, thanks for feedback. I will try to look into this once again properly, and especially with keeping new way of SSL authentication that ZEO5 started to use, after we hopefully settle with https://github.com/zopefoundation/ZEO/pull/217.

**Comment by navytux** [comment]
Jens, Dieter, I looked at this PR again after rereading documentation wrt SSL. I've made corrections in https://github.com/zopefoundation/ZEO/pull/220/commits/c7f2138a6cfe5401c0e2d5bd6a7713e631eba9e3 and https://github.com/zopefoundation/ZEO/pull/220/commits/b3318e818cf95f37502b5cb03910b30abf8d314b.

After those corrections I believe hereby change should be ok to go.

**Review by dataflake — APPROVED** [review]
👍

**Review by d-maurer — APPROVED** [review]
You might also want to remove `AuthError` from `ZEO.Exceptions` (it appears to no longer be used).

**Comment by navytux** [comment]
Thanks, Dieter. I did so in 12af50c5.

**Pull request merged**
