### PR TITLE
'msgpack-python' egg was renamed 'msgpack'

### PR DESCRIPTION
**Pull request by jmuchemb**
https://github.com/msgpack/msgpack-python/#very-important-notes-for-existing-users

### CODE REVIEW

**Comment by mgedmin** [comment]
Should I retry the failed Python 3.6 tests to see if they're non-deterministic failures?  Or is anyone planning to analyze the failure and would rather I didn't destroy the current logs?

(I don't think Travis can let you see the logs of jobs that you've retried.  If I'm mistaken, I'd love to hear a correction!)

**Comment by icemac** [comment]
@jmuchemb Could you please rebase your PR onto master, as it has now successfully running tests again.

**Comment by icemac** [comment]
Using a `msgpack` version < 0.6 fixes the tests.
Can we merge this PR having a follow-up issue to update to the current version or should the issues be fixed in this PR? Any preference?

**Comment by jamadden** [comment]
If the failures are simple and the fixes obvious, I think it'd be fine to fix them here while also updating the pin. 

However, from glancing at the log, neither the failures nor the fixes look simple (to me). In that case, it seems reasonable to merge this simple PR, so that master is working/releasable, and defer the version update to a later PR (so long as there's an issuer so we don't forget).

**Comment by icemac** [comment]
I created #122 for the update to a current `msgpack` version.
Should this change have a change log entry or is it now ready to merge?

**Pull request merged**
