### PR TITLE
Fix #22

### LINKED ISSUE #22: Test failures on Mac
checkReconnectSwitch (ZEO.tests.testConnection.FileStorageReconnectionTests)
   invalidations_while_connecting (ZEO.tests.testConnection)
   gracefully_handle_abort_while_storing_many_blobs (ZEO.tests.testZEO)

Select fails with: OSError: [Errno 9] Bad file descriptor

This seems vaguely familiar. :(

### PR DESCRIPTION
**Pull request by jimfulton**

### CODE REVIEW

**Comment by tseaver** [comment]
Oh, the humanity!

**Comment by jimfulton** [comment]
what?

**Comment by jimfulton** [comment]
There's a detailed description of the issue in a comment in the code/diff

**Comment by tseaver** [comment]
I was [commenting](https://www.youtube.com/watch?v=F54rqDh2mWA) on the need for the change (which is worse because testing for it would require monkey-patching `select`).

**Comment by jimfulton** [comment]
Or just running the tests on a mac. :)

**Comment by jimfulton** [comment]
Travis is green.

**Comment by jimfulton** [comment]
no...

**Comment by jimfulton** [comment]
Yay, tests pass!  So in addition to fixing the mac test failures, this has another real test fix, plus a travis change to make other spurious failures less likely.

**Comment by tseaver** [comment]
Do we need to tweak `travis.yml` so that we run Travis tests on Mac environments too?  E.g.:

  https://github.com/zopefoundation/BTrees/blob/master/.travis.yml#L18-L25

**Comment by jimfulton** [comment]
I didn't know that was an option.  I guess I'll add that.

**Comment by jimfulton** [comment]
OK, I made a stab at updating travis to run tests on mac. Now the tests have been queued for 30 minutes. No errors. I assume I did something wrong. Can someone fix this?

Otherwise, I'll revert the travis change.

Oh, the humanity!

**Comment by tseaver** [comment]
Travis seems pretty backed up today:  I think we may get penalized because the ZEO tests take so long to run.

**Comment by jimfulton** [comment]
This is ridiculous.

**Comment by jimfulton** [comment]
Travis is green.

**Pull request merged**
