### PR TITLE
Fix test with ZODB >= 5.6.0

### PR DESCRIPTION
**Pull request by jmuchemb**
See https://github.com/zopefoundation/ZODB/pull/207

### CODE REVIEW

**Comment by jmuchemb** [comment]
Note however that the test in question (checkTransactionExtensionFromIterator) is meaningless with msgpack protocol because the network serialization transforms the extension object into a simple dict. The ZEO protocol should be optimized to serialize extensions on client side (thanks to the new `extension_bytes` property).

**Comment by jmuchemb** [comment]
`copy_reg` also does not exist in Python 3.

The ZODB change is about to avoid deserialize+reserialize extensions because otherwise the resulting bytes could change and a dump/restore tool would produce something that's not bit-to-bit identical to its original. The failing test reproduce such case with something similar to:
- `b'\x80\x02c__builtin__\ndict\nq\x01)\x85Rq\x02.'` is loaded as `{}`
- and `{}` is dumped as `b'\x80\x02}.'`

2 pickles coding the same information. The test expects first one to be stored on-disk, which is not the case in ZEO (whether msgpack is used or not) because of a dummy and transparent serialize+deserialize step at network level:
- This serialize+deserialize step is inefficient (I mean that both pickle and msgpack are certainly faster at serializing+deserializing bytes rather than a dict object).
- The whole checkTransactionExtensionFromIterator test checks nothing in the case ZEO.

**Comment by jmuchemb** [comment]
What I don't like with this PR is that it hides things that should be done.

**Comment by jamadden** [comment]
It looks like this might be affecting other projects, like [zc.zrs (see linked issue)](https://github.com/zopefoundation/zc.zrs/issues/6) It might be good to finish this up and make a release. (Which needs either @tseaver or @jimfulton)

**Comment by dataflake** [comment]
I think this is as ready as it can be for a merge now. What I learned:

- the battery of tests does not run on macOS at all. It seems to abuse threads and sockets in a way that leads to crashes coming out of system libraries
- even if there is no real problem, getting `tox` to run through (or Travis CI) is nothing but luck. The test battery has timing/race condition issues that lead to random failures on Travis and to specific recurring failures in ZEO prefetch tests when running `tox` locally.
- Python 3.8 compatibility will be yet another big step. The unit test level consistently produces tracebacks like the one below when running `tox` locally.

But on the other hand I am glad there are so many tests that seem to cover so many variants. It's just hard for me to distinguish what failures are due to bad tests and what failures constitute real issues.

```
Error in test test_multiple_addresses (ZEO.asyncio.tests.ClientTests)
Traceback (most recent call last):
  File "/opt/zope/Python-3.8.4/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/zope/Python-3.8.4/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/zope/Python-3.8.4/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/tests.py", line 427, in test_multiple_addresses
    self.respond(1, None)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/tests.py", line 116, in respond
    self.loop.protocol.data_received(
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/base.py", line 128, in data_received
    self.message_received(collected)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 232, in message_received
    future.set_result(args)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 904, in set_result
    self.cb(self)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 45, in _
    f = gen.send(result)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 202, in finish_connect
    self.client.registered(self, server_tid)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 447, in registered
    self._clear_protocols(protocol)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 404, in _clear_protocols
    p.close()
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 98, in close
    self._connecting.cancel()
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/testing.py", line 31, in call_soon
    func(*args)
  File "/home/zope/src/ZEO/.tox/py38/lib/python3.8/site-packages/ZEO/asyncio/client.py", line 129, in done_connecting
    if future.exception() is not None:
asyncio.exceptions.CancelledError
```

**Comment by dataflake** [comment]
@tseaver Could you make a release or add me to the package maintainers? I was also very surprised to see that the change log claims there was a 5.2.1 released in February 2019 yet PyPI doesn't list it.

**Comment by dataflake** [comment]
@tseaver @jimfulton Could you make a release or add me to the package maintainers?

**Comment by tseaver** [comment]
@dataflake I've added you as a maintainer.

**Comment by dataflake** [comment]
@tseaver you added me to ZODB, I asked about ZEO 😉

**Comment by tseaver** [comment]
D'oh.  Rectified.

**Comment by dataflake** [comment]
ZEO 5.2.2 is now released

**Pull request merged**
