### PR TITLE
asyncio.base.Protocol: Rename _write -> write_message,  _writeit -> write_message_iter

### PR DESCRIPTION
**Pull request by navytux**
--------
kirr:

Those methods are not private to Protocol, because they are invoked e.g. from
other modules besides ZEO.asyncio.base - e.g. from ZEO.asyncio.server . Make
them public via dropping "_" prefix and naming them using more descriptive names.

Extracted from https://github.com/zopefoundation/ZEO/pull/195

### CODE REVIEW

**Review by dataflake — APPROVED** [review]
The code looks OK but I have no context or knowledge about the reasons for the change.

**Comment by navytux** [comment]
Thanks, @dataflake.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2022-6-1 02:48 -0700:
***@***.*** approved this pull request.
>
>The code looks OK but I have no context or knowledge about the reasons for the change.

I did not like the names `_write` and `_writeit`
and replaced them with the more informative `write_message`
and `write_message_iter`. It's just cosmetics.

**Comment by navytux** [comment]
Thanks, @d-maurer.

**Pull request merged**
