### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by dataflake**
First step, just enabling tests. Further work is expected.

### CODE REVIEW

**Comment by dataflake** [comment]
Testing ZEO under Python 3.10 leads to connection timeouts like the one pasted below. The timeout is apparently hiding the real issue.

```
Error in test check2StorageThreads (ZEO.tests.testZEO.FileStorageSSLTests)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/case.py", line 587, in run
    self._callSetUp()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/case.py", line 546, in _callSetUp
    self.setUp()
  File "/home/runner/work/ZEO/ZEO/.tox/py310/lib/python3.10/site-packages/ZEO/tests/testZEO.py", line 253, in setUp
    ClientStorage(
  File "/home/runner/work/ZEO/ZEO/.tox/py310/lib/python3.10/site-packages/ZEO/ClientStorage.py", line 281, in __init__
    self._wait()
  File "/home/runner/work/ZEO/ZEO/.tox/py310/lib/python3.10/site-packages/ZEO/asyncio/client.py", line 856, in wait
    self.wait_for_result(self.client.connected, timeout)
  File "/home/runner/work/ZEO/ZEO/.tox/py310/lib/python3.10/site-packages/ZEO/asyncio/client.py", line 790, in wait_for_result
    raise ClientDisconnected("timed out waiting for connection")
ZEO.Exceptions.ClientDisconnected: timed out waiting for connection
```

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2022-3-19 06:01 -0700:
>Testing ZEO under Python 3.10 leads to connection timeouts like the one pasted below. The timeout is apparently hiding the real issue.

The tests with errors are all SSL tests.

I debugged one of those tests and got:
Message: 'Connection to %r failed, %s'
Arguments: ((('127.0.0.1', 10089), SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')),)
INFO:ZEO.asyncio.client:retry connecting ('127.0.0.1', 10089)
DEBUG:asyncio:Close <_UnixSelectorEventLoop running=False closed=False debug=True>
DEBUG:ZEO.asyncio.client:Stopping client thread


Apparently, Python 3.10 distinguishes between a
PROTOCOL_TLS_SERVER and a PROTOCOL_TLS_CLIENT context
and we (wrongly) use a server context.

**Comment by d-maurer** [comment]
Not too bad: 1 failing race condition check and (apparently) one deadlock (probably a race condition, too).

**Comment by dataflake** [comment]
Surprise, all tests now pass after merging in the latest changes from the master branch. Please review when you have a moment.

**Review by d-maurer — APPROVED** [review]

**Pull request merged**
