### PR TITLE
Add automated tests against the ZODB master branch

### LINKED ISSUE #177: Add a test against ZODB master branch to GH actions

### PR DESCRIPTION
**Pull request by dataflake**
Fixes #177 

This PR does the following:

- cut down `tox.ini` environment descriptions by using shorthand notation
- ignore `ResourceWarnings` on `tox` runs for Python 3
- add an automated  GitHub Actions test run using Python 3.7 against the ZODB ``master`` branch.

I didn't know how to express something like "the dependency ZODB needs to be checked out" in `tox.ini` itself, so I took a detour via a dedicated `zc.buildout` configuration. Let me know if you have a more elegant solution.

### CODE REVIEW

**Comment by navytux** [comment]
@dataflake, thanks for doing this.

> I didn't know how to express something like "the dependency ZODB needs to be checked out" in tox.ini itself, so I took a detour via a dedicated zc.buildout configuration. Let me know if you have a more elegant solution.

Here is example how one can add environment to tox test matrix to verify things wrt ZODB checkout:

https://lab.nexedi.com/nexedi/zodbtools/commit/c50bfb00

Another thing, noted during working on recent fixes to ZEO, is that concurrency bugs are much more likely to trigger on python2. This way I would suggest to have both `py27-zodb-master` and `py37-zodb-master`.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2021-4-24 05:26 -0700:
> ...
>I didn't know how to express something like "the dependency ZODB needs to be checked out" in `tox.ini` itself, so I took a detour via a dedicated `zc.buildout` configuration. Let me know if you have a more elegant solution.

Usually, "pip" is used to install requirements.
"pip" supports "VCS project urls" as package specifiers
and "git" is one of the supported "Version Control Systems".

"VCS project urls" have the form: *scheme*+*url*
*url* is interpreted by the the VCS identified by *scheme*.
Thus, it can use any means supported by the VCS to identify
branches or revisions.

`git+https://github.com/pypa/pip.git` is an example for a git project url.
Apparently (from "https://matiascodesal.com/blog/how-use-git-repository-pip-dependency/"), "git" is using @ suffixes to specify a revision.
Thus ***@***.***` should specify
the `master` branch.

**Comment by jugmac00** [comment]
Here are some more examples:
https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support

**Comment by dataflake** [comment]
Thank you all for your help, I managed to drop the buildout step and make the PR much smaller. Please take a look and leave a review when you have a minute.

**Comment by navytux** [comment]
Thanks, @dataflake. I have not verified in detail, but the changes look reasonable to me. The failure in `check_race_loadopen_vs_local_invalidate`  in py27-zodbmaster is expected as we don't have https://github.com/zopefoundation/ZEO/pull/174 merged yet. The failure with "bad file descriptor" is also known (see https://github.com/zopefoundation/ZEO/issues/176). In general I believe it is ok to merge this.

**Review by navytux — APPROVED** [review]

**Pull request merged**
